In [1]:
from pathlib import Path
from dotenv import load_dotenv
import os
import pandas as pd

ROOT = Path.cwd().parent

env_path = ROOT / ".env.backtest"

load_dotenv(env_path)

print(env_path)
print(os.getenv("MONGO_HOST"))

os.chdir(Path.cwd().parent)

/Users/paulvogt/mongo_db_streamlit/.env.backtest
localhost

In [2]:
%pwd

'/Users/paulvogt/mongo_db_streamlit'

In [3]:
from infrastructure.mongo.mongo_repository import MongoRepository
from config.mongo_config import MongoCollection, MongoDatabase, MongoUser
from infrastructure.mongo.mongo_connection import MongoConnection
from core.application.notebook_service import NotebookService

In [4]:
import pandas as pd
from config.pipeline_config import CONSTITUES

with MongoConnection(user=MongoUser.APPUSER) as conn:
    constituents_repo = MongoRepository(
        conn,
        MongoDatabase.PROCESSED,
        MongoCollection.SCD_CONSTITUENTS
    )
    raw_cons = MongoRepository(
        conn,
        MongoDatabase.RAW,
        MongoCollection.CONSTITUENTS
    )
    #scd_df = pd.DataFrame(
    #    list(
    #        constituents_repo.find(
    #            projection={"symbol": 1, "fromDate": 1, "toDate": 1, "_id": 0}
    #        )
    #    )
    #)

    raw_cons.execute_pipeline(CONSTITUES)
    raw_cons.create_index(keys=[("removedTicker", 1), ("date", 1)], unique=False)

    con_df = pd.DataFrame(
        list(
            raw_cons.find(sort={"date": 1})
        )
    )

In [15]:
con_df.head()

,_id,dateAdded,addedSecurity,removedTicker,removedSecurity,date,symbol,reason
0,69c650428de5ed10f4027048,"March 04, 1957",Curtiss Wright Corp,,,1957-03-03,CW,
1,69c650428de5ed10f4027051,"March 04, 1957",Dayton Power & Light Co,,,1957-03-03,DPL,
2,69c650428de5ed10f4027050,"March 04, 1957",Dow Chemical Company,,,1957-03-03,DOW,
3,69c650428de5ed10f402704f,"March 04, 1957",Dan River Inc,,,1957-03-03,DML,
4,69c650428de5ed10f402704e,"March 04, 1957",Dome Mines Ltd,,,1957-03-03,DM,

In [28]:
tick_added = con_df[["symbol", "addedSecurity"]].drop_duplicates()
tick_added.loc[tick_added["symbol"] == "", "symbol"] = None
tick_added.loc[tick_added["addedSecurity"] == "", "addedSecurity"] = None
tick_added = tick_added.dropna(how="all").reset_index(drop=True)
tick_added.head(5)

  symbol            addedSecurity
0     CW      Curtiss Wright Corp
1    DPL  Dayton Power & Light Co
2    DOW     Dow Chemical Company
3    DML            Dan River Inc
4     DM           Dome Mines Ltd

In [30]:
tick_removed = con_df[["removedTicker", "removedSecurity"]].drop_duplicates()
tick_removed.loc[tick_removed["removedTicker"] == "", "removedTicker"] = None
tick_removed.loc[tick_removed["removedSecurity"] == "", "removedSecurity"] = None
tick_removed = tick_removed.dropna(how="all").reset_index(drop=True).rename(columns={"removedTicker" : "symbol"})
tick_removed.head(5)

  symbol              removedSecurity
0     GN    Great Northern Railway Co
1     NP  Northern Pacific Railway Co
2    PUL     Publicker Industries Inc
3    ABW        Associated Brewing Co
4    BGT        Budget Industries Inc

In [36]:
df_merged = pd.merge(tick_added, tick_removed, how='outer', on="symbol" )
df_merged.head()

  symbol              addedSecurity                     removedSecurity
0      A  Agilent Technologies Inc.                         Anaconda Co
1     AA                        NaN                           Alcoa Inc
2    AAF                        NaN             American Air Filter Inc
3    AAL    American Airlines Group  Alexander & Alexander Services Inc
4    AAL    American Airlines Group             American Airlines Group

AAL 
```{
        "dateAdded": "March 04, 1957",
        "addedSecurity": "American Airlines Group",
        "removedTicker": "",
        "removedSecurity": "",
        "date": "1957-03-03",
        "symbol": "AAL",
        "reason": ""
    },
{
        "dateAdded": "October 6, 1988",
        "addedSecurity": "Alexander & Alexander Services Inc",
        "removedTicker": "GLD",
        "removedSecurity": "Gould Inc",
        "date": "1988-10-06",
        "symbol": "AAL",
        "reason": "Annual Re-ranking"
    },
{
        "dateAdded": "January 14, 1997",
        "addedSecurity": "CNO Financial Group",
        "removedTicker": "AAL",
        "removedSecurity": "Alexander & Alexander Services Inc",
        "date": "1997-01-14",
        "symbol": "CNO",
        "reason": "Annual Re-ranking"
    },
{
        "dateAdded": "March 20, 2015",
        "addedSecurity": "American Airlines Group Inc",
        "removedTicker": "AGN",
        "removedSecurity": "Allergan Inc.",
        "date": "2015-03-20",
        "symbol": "AAL",
        "reason": "Allergan acquired by Actavis (and changed name to Allergan)."
    },
{
        "dateAdded": "September 23, 2024",
        "addedSecurity": "Palantir Technologies",
        "removedTicker": "AAL",
        "removedSecurity": "American Airlines Group",
        "date": "2024-09-23",
        "symbol": "PLTR",
        "reason": "Market capitalization change."
    }

AAL wird 3 mal eingefügt und nur 2 mal rausgenommen.

In [48]:
df_1957 = con_df[["symbol", "addedSecurity", "date"]]
df_1957 = df_1957.loc[df_1957["date"] == "1957-03-03"]
df_1957.describe()

                      date
count                  151
mean   1957-03-03 00:00:00
min    1957-03-03 00:00:00
25%    1957-03-03 00:00:00
50%    1957-03-03 00:00:00
75%    1957-03-03 00:00:00
max    1957-03-03 00:00:00

In [45]:
df_only_added = con_df
df_only_added = df_only_added.loc[df_only_added["removedTicker"] == ""].reset_index(drop=True)
df_only_added.tail(50)

,_id,dateAdded,addedSecurity,removedTicker,removedSecurity,date,symbol,reason
204,69c650428de5ed10f402700a,"March 04, 1957",Public Service Enterprise Group,,,1957-03-04,PEG,
205,69c650428de5ed10f4026fe3,"June 30, 1964",Sherwin-Williams,,,1964-06-30,SHW,
206,69c650428de5ed10f4026fe2,"March 31, 1965",Cummins,,,1965-03-31,CMI,
207,69c650428de5ed10f4026fe1,"March 31, 1965",Emerson Electric,,,1965-03-31,EMR,
208,69c650428de5ed10f4026fe0,"March 31, 1969",Clorox,,,1969-03-31,CLX,
209,69c650428de5ed10f4026fdf,"June 30, 1969",Newmont,,,1969-06-30,NEM,
210,69c650428de5ed10f4026e5e,"December 10, 1987",Fleming Companies,,,1987-12-10,FLM,Annual Re-ranking
211,69c650428de5ed10f4026d4a,"January 3, 2000",NCR Corp.,,,2000-01-03,NCR,Annual Re-ranking
212,69c650428de5ed10f4026d37,"June 16, 2000",Charter One Financial Inc,,,2000-06-16,CF,Annual Re-ranking
213,69c650428de5ed10f4026d1b,"December 4, 2000",Robert Half Int'l Inc,,,2000-12-04,RHI,Annual Re-ranking
214,69c650428de5ed10f4026cfa,"September 20, 2001",Immunex Corp.,,,2001-09-20,IMNX,Annual Re-ranking
215,69c650428de5ed10f4026cf3,"December 13, 2001",Genzyme Corp.,,,2001-12-13,GENZ,Annual Re-ranking
216,69c650428de5ed10f4026cdb,"September 3, 2002",Reynolds American Inc.,,,2002-09-03,RAI,Annual Re-ranking
217,69c650428de5ed10f4026cc1,"December 2, 2004",Freescale Semiconductor Inc,,,2004-12-02,FSLB,Annual Re-ranking
218,69c650428de5ed10f4026cb0,"October 3, 2005",Lennar Corp.,,,2005-10-03,LEN,Annual Re-ranking
219,69c650428de5ed10f4026ca8,"January 4, 2006",Estee Lauder Companies Inc,,,2006-01-04,EL,Annual Re-ranking
220,69c650428de5ed10f4026c72,"September 25, 2007",Intercontinental Exchange Inc,,,2007-09-25,ICE,FDC acquired by KKR.
221,69c650428de5ed10f4026c52,"September 12, 2008",Fastenal Co.,,,2008-09-12,FAST,Capitalization rebalance.
222,69c650428de5ed10f4026c51,"September 12, 2008",Salesforce.com Inc,,,2008-09-12,CRM,Capitalization rebalance.
223,69c650428de5ed10f4026c4f,"September 19, 2008",L3Harris Technologies Inc,,,2008-09-19,LHX,Annual Re-ranking
224,69c650428de5ed10f4026c4d,"September 23, 2008",Pioneer Natural Resources Co,,,2008-09-23,PXD,Annual Re-ranking
225,69c650428de5ed10f4026c4a,"October 1, 2008",Flowserve Corporation,,,2008-10-01,FLS,Annual Re-ranking
226,69c650428de5ed10f4026c44,"November 12, 2008",People's United Financial Inc,,,2008-11-12,PBCT,Annual Re-ranking
227,69c650428de5ed10f4026c40,"November 14, 2008",Cephalon Inc.,,,2008-11-14,CEPH,Annual Re-ranking
228,69c650428de5ed10f4026c2b,"June 8, 2009","DeVry, Inc.",,,2009-06-08,ATGE,Annual Re-ranking
229,69c650428de5ed10f4026c29,"June 29, 2009",,,,2009-06-29,TMUS,Annual Re-ranking
230,69c650428de5ed10f4026bd0,"April 3, 2014",Alphabet Inc. Class C,,,2014-04-03,GOOG,Annual Re-ranking
231,69c650428de5ed10f4026bc9,"August 6, 2014",Discovery Communications Inc Class C (Warner B...,,,2014-08-06,DISCK,Class C share distribution
232,69c650428de5ed10f4026bb1,"September 18, 2015",Comcast Class A Spec.,,,2015-09-18,CMCSK,Share class methodology change
233,69c650428de5ed10f4026bb0,"September 18, 2015",News Corp Class B,,,2015-09-18,NWS,Share class methodology change\n
234,69c650428de5ed10f4026baf,"September 18, 2015",,,,2015-09-18,FOX,Share class methodology change\n
235,69c650428de5ed10f4026b9d,"April 14, 2016",Under Armour Inc Class C,,,2016-04-14,UA,Annual Re-ranking
236,69c650428de5ed10f4026b91,"July 1, 2016",Fortive Corp,,,2016-07-01,FTV,CPGX acquired by TRP
237,69c650428de5ed10f4026b72,"August 8, 2017",Brighthouse Financial Inc,,,2017-08-08,BHF,"BHF replaced AN,"
238,69c650428de5ed10f4026b6b,"January 2, 2018",Huntington Ingalls Industries Inc.,,,2018-01-02,HII,Becton Dickinson acquired BCR.
239,69c650428de5ed10f4026b50,"April 1, 2019",Dow Inc,,,2019-04-01,DOW,DOW spun off from DWDP
240,69c650428de5ed10f4026b3c,"April 2, 2020",Carrier Global Corp,,,2020-04-02,CARR,United Technologies spun off Otis and Carrier ...
241,69c650428de5ed10f4026b3b,"April 2, 2020",Otis Worldwide Corp,,,2020-04-02,OTIS,United Technologies spun off Otis and Carrier ...
242,69c650428de5ed10f4026b2e,"October 8, 2020",Vontier Corp.,,,2020-10-08,VNT,S&P 500 constituent Fortive spun off Vontier.
243,69c650428de5ed10f4026b22,"June 2, 2021",Organon & Co,,,2021-06-02,OGN,S&P 500/100 constituent Merck & Co. spun off O...
244,69c650428de5ed10f4026b14,"March 1, 2022",Molina Healthcare Inc,,,2022-03-01,MOH,S&P 500 constituent S&P Global Inc. acquired I...
245,69c650428de5ed10f4026b07,"December 15, 2022",MasterBrand Inc,,,2022-12-15,MBC,S&P 500 constituent Fortune Brands Home & Secu...
246,69c650428de5ed10f4026b03,"January 3, 2023",GE HealthCare Technologies Inc,,,2023-01-03,GEHC,S&P 500 constituent General Electric spun off ...
247,69c650428de5ed10f4026af9,"September 29, 2023",Veralto Corp,,,2023-09-29,VLTO,S&P 500 and S&P 100 constituent Danaher Corpor...
248,69c650428de5ed10f4026af0,"April 1, 2024",Solventum Corp,,,2024-04-01,SOLV,S&P 500 and 100 constituent 3M Co. spun off So...
249,69c650428de5ed10f4026aef,"April 1, 2024",GE Vernova Inc,,,2024-04-01,GEV,S&P 500 and 100 constituent General Electric C...
250,69c650428de5ed10f4026aeb,"May 8, 2024",Vistra,,,2024-05-08,VST,S&P 500 and S&P 100 constituent ExxonMobil acq...
251,69c650428de5ed10f4026aea,"June 24, 2024",GoDaddy,,,2024-06-24,GDDY,Market capitalization change.
252,69c650428de5ed10f4026ae8,"June 24, 2024",CrowdStrike,,,2024-06-24,CRWD,Market capitalization change.
253,69c650428de5ed10f4026ae6,"June 24, 2024",KKR,,,2024-06-24,KKR,Market capitalization change.

In [46]:
df_only_removed = con_df
df_only_removed = df_only_removed.loc[df_only_removed["addedSecurity"] == ""].reset_index(drop=True)
df_only_removed.tail(50)

,_id,dateAdded,addedSecurity,removedTicker,removedSecurity,date,symbol,reason
27,69c650428de5ed10f4026d02,"August 2, 2001",,OAT,Quaker Oats Co,2001-08-02,PMCS,Annual Re-ranking
28,69c650428de5ed10f4026cfb,"September 17, 2001",,TOS,Tosco Corp.,2001-09-17,TOS,Annual Re-ranking
29,69c650428de5ed10f4026cf4,"December 12, 2001",,RAL,Ralston Purina Co.,2001-12-12,RAL,Annual Re-ranking
30,69c650428de5ed10f4026cdc,"August 30, 2002",,COC-B,Conoco Inc.,2002-08-30,COC-B,Annual Re-ranking
31,69c650428de5ed10f4026cc2,"November 30, 2004",,WLP,Wellpoint Health Networks Inc,2004-11-30,LLL,Annual Re-ranking
32,69c650428de5ed10f4026cc0,"December 17, 2004",,CR,Crane Co.,2004-12-17,ASN,Annual Re-ranking
33,69c650428de5ed10f4026cbf,"December 17, 2004",,DLX,Deluxe Corp.,2004-12-17,FOXA,Annual Re-ranking
34,69c650428de5ed10f4026cb1,"September 30, 2005",,G,Gillette Co.,2005-09-30,G,Annual Re-ranking
35,69c650428de5ed10f4026ca9,"January 3, 2006",,MERQ,Mercury Interactive Corp,2006-01-03,MERQ,Annual Re-ranking
36,69c650428de5ed10f4026c73,"September 24, 2007",,FDC,First Data Corp.,2007-09-24,FDC,FDC acquired by KKR.
37,69c650428de5ed10f4026c54,"September 10, 2008",,FNMA,Fannie Mae (FNMA),2008-09-10,FNMA,Annual Re-ranking
38,69c650428de5ed10f4026c53,"September 10, 2008",,FMCC,Freddie Mac (FHLMC),2008-09-10,FMCC,Annual Re-ranking
39,69c650428de5ed10f4026c50,"September 16, 2008",,LEHMQ,Lehman Brothers Holding,2008-09-16,LEHMQ,Annual Re-ranking
40,69c650428de5ed10f4026c4e,"September 22, 2008",,SAF,Safeco Corp.,2008-09-22,SAF,Annual Re-ranking
41,69c650428de5ed10f4026c4c,"September 29, 2008",,COOP,Mr. Cooper Group Inc,2008-09-29,COOP,Annual Re-ranking
42,69c650428de5ed10f4026c45,"November 10, 2008",,UIS,Unisys Corp.,2008-11-10,UIS,Annual Re-ranking
43,69c650428de5ed10f4026c43,"November 12, 2008",,GGP,GGP Inc,2008-11-12,GGP,Annual Re-ranking
44,69c650428de5ed10f4026c38,"December 31, 2008",,WB,Wachovia Corp.,2008-12-31,OI,Annual Re-ranking
45,69c650428de5ed10f4026c2d,"June 2, 2009",,GM,General Motors Co,2009-06-02,GM,Annual Re-ranking
46,69c650428de5ed10f4026c2a,"June 25, 2009",,TEL,TE Connectivity Ltd,2009-06-25,TEL,Tyco Electronics left the index because it was...
47,69c650428de5ed10f4026c29,"June 29, 2009",,,,2009-06-29,TMUS,Annual Re-ranking
48,69c650428de5ed10f4026c1c,"December 18, 2009",,KBH,KB Home,2009-12-18,CLF,Market capitalization change.
49,69c650428de5ed10f4026baf,"September 18, 2015",,,,2015-09-18,FOX,Share class methodology change\n
50,69c650428de5ed10f4026ba9,"December 11, 2015",,CMCSK,Comcast Class A Spec.,2015-12-11,CMCSK,CMCSK shares no longer listed
51,69c650428de5ed10f4026b90,"July 5, 2016",,CPGX,Columbia Pipeline Group Inc.,2016-07-05,CPGX,CPGX acquired by TRP
52,69c650428de5ed10f4026b8f,"September 6, 2016",,TYC,Tyco International,2016-09-06,MTD,TYC acquires JCI (and retains JCI ticker).
53,69c650428de5ed10f4026b89,"December 1, 2016",,OI,,2016-12-01,MAA,Market capitalization change.
54,69c650428de5ed10f4026b73,"August 7, 2017",,AN,AutoNation Inc.,2017-08-07,AN,"BHF replaced AN,"
55,69c650428de5ed10f4026b6c,"December 28, 2017",,BCR,C. R. Bard Inc,2017-12-28,BCR,Becton Dickinson acquired BCR.
56,69c650428de5ed10f4026b67,"March 19, 2018",,SIG,Signet Jewelers Ltd,2018-03-19,TTWO,Market capitalization change.
57,69c650428de5ed10f4026b4f,"April 2, 2019",,BHF,Brighthouse Financial Inc,2019-04-02,BHF,DOW spun off from DWDP
58,69c650428de5ed10f4026b4a,"July 12, 2019",,RHT,Red Hat Inc.,2019-07-12,TMUS,S&P 500 & 100 constituent IBM acquired Red Hat.
59,69c650428de5ed10f4026b3a,"April 6, 2020",,M,Macy’s Inc,2020-04-06,M,Market capitalization change.
60,69c650428de5ed10f4026b39,"April 6, 2020",,RTN,Raytheon Co.,2020-04-06,RTN,United Technologies spun off Otis and Carrier ...
61,69c650428de5ed10f4026b33,"June 19, 2020",,JWN,Nordstrom Inc,2020-06-19,BIO,Market capitalization change.
62,69c650428de5ed10f4026b2d,"October 9, 2020",,NBL,Noble Energy Inc,2020-10-09,NBL,Chevron acquired Noble Energy.
63,69c650428de5ed10f4026b21,"June 3, 2021",,HFC,HollyFrontier Corp,2021-06-03,HFC,Market capitalization change.
64,69c650428de5ed10f4026b1f,"August 27, 2021",,MXIM,Maxim Integrated Products Inc,2021-08-27,TECH,S&P 500 constituent Analog Devices acquired Ma...
65,69c650428de5ed10f4026b15,"February 25, 2022",,INFO,IHS Markit Ltd,2022-02-25,INFO,S&P 500 constituent S&P Global Inc. acquired I...
66,69c650428de5ed10f4026b12,"April 11, 2022",,DISCK,Discovery Communications Inc Class C (Warner B...,2022-04-11,DISCK,Annual Re-ranking
67,69c650428de5ed10f4026b0e,"June 17, 2022",,UA,Under Armour Inc Class A,2022-06-17,UA,Market capitalization change.
68,69c650428de5ed10f4026b06,"December 19, 2022",,MBC,MasterBrand Inc,2022-12-19,MBC,Market capitalization change.
69,69c650428de5ed10f4026b02,"January 5, 2023",,VNO,Vornado Realty Trust,2023-01-05,VNO,Market capitalization change.
70,69c650428de5ed10f4026af8,"October 2, 2023",,DXC,DXC Technology Co,2023-10-02,DXC,Market capitalization change.
71,69c650428de5ed10f4026aee,"April 2, 2024",,VFC,V.F. Corp,2024-04-02,VFC,Market capitalization change.
72,69c650428de5ed10f4026aed,"April 2, 2024",,XRAY,Dentsply Sirona Inc,2024-04-02,XRAY,Market capitalization change.
73,69c650428de5ed10f4026aec,"May 8, 2024",,PXD,Pioneer Natural Resources,2024-05-08,PXD,S&P 500 and S&P 100 constituent ExxonMobil acq...
74,69c650428de5ed10f4026ae9,"June 24, 2024",,ILMN,"Illumina, Inc.",2024-06-24,ILMN,Market capitalization change.
75,69c650428de5ed10f4026ae7,"June 24, 2024",,CMA,Comerica,2024-06-24,CMA,Market capitalization change.
76,69c650428de5ed10f4026ae5,"June 24, 2024",,RHI,Robert Half,2024-06-24,RHI,Market capitalization change.

LLL

```{
        "dateAdded": "June 28, 2019",
        "addedSecurity": "MarketAxess Holdings Inc",
        "removedTicker": "LLL",
        "removedSecurity": "L3 Technologies Inc",
        "date": "2019-06-28",
        "symbol": "MKTX",
        "reason": "L3 purchased by Harris Corporation"
    },
    {
        "dateAdded": "November 30, 2004",
        "addedSecurity": "",
        "removedTicker": "WLP",
        "removedSecurity": "Wellpoint Health Networks Inc",
        "date": "2004-11-30",
        "symbol": "LLL",
        "reason": "Annual Re-ranking"
    },

    IN MEINER COMPANY DATA:
    {
  "_id": {
    "$oid": "69ac0300fdf7b4ac98cc7a02"
  },
  "symbol": "LLL",
  "companyName": "JX Luxventure Limited",
  "image": "https://images.financialmodelingprep.com/symbol/LLL.png",
  "sector": "Consumer Cyclical"
}
````
LLL wird hinzugefügt aber ohne addedSecurity. Dann wird es removed aber mit "removedSecurity": "L3 Technologies Inc". Der eigentliche Name in der CompanyData Datei ist "companyName": "JX Luxventure Limited" mit dem "ipoDate": "2013-03-07",